relationship-hub-api:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${relationship-hub-api.datasource.host}:${relationship-hub-api.datasource.port}/${relationship-hub-api.datasource.db}
    username: ${relationship-hub-api.datasource.username}
    password: ${relationship-hub-api.datasource.password}
    hikari:
      maximum-pool-size: 1
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
  springdoc:
    swagger-ui:
      enabled: true
  swagger-servers-urls: ${relationship-hub-api.swagger-servers-urls}
