relationship-hub-api:
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:relationship_hub_api;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    url: jdbc:h2:file:relationship_hub_api;MODE=PostgreSQL
    username: relationship_hub_api
    password: relationship_hub_api
    pool-size: 1
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
          web-allow-others: true
  springdoc:
    swagger-ui:
      enabled: true
  swagger-servers-urls: https://hub.luanfernandes.dev
